# Generated by Django 5.1.6 on 2025-04-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius1', models.FloatField()),
                ('texture1', models.FloatField()),
                ('perimeter1', models.FloatField()),
                ('area1', models.FloatField()),
                ('smoothness1', models.FloatField()),
                ('compactness1', models.FloatField()),
                ('concavity1', models.FloatField()),
                ('concave_points1', models.FloatField()),
                ('symmetry1', models.FloatField()),
                ('fractal_dimension1', models.FloatField()),
                ('radius2', models.FloatField()),
                ('texture2', models.FloatField()),
                ('perimeter2', models.FloatField()),
                ('area2', models.FloatField()),
                ('smoothness2', models.FloatField()),
                ('compactness2', models.FloatField()),
                ('concavity2', models.FloatField()),
                ('concave_points2', models.FloatField()),
                ('symmetry2', models.FloatField()),
                ('fractal_dimension2', models.FloatField()),
                ('radius3', models.FloatField()),
                ('texture3', models.FloatField()),
                ('perimeter3', models.FloatField()),
                ('area3', models.FloatField()),
                ('smoothness3', models.FloatField()),
                ('compactness3', models.FloatField()),
                ('concavity3', models.FloatField()),
                ('concave_points3', models.FloatField()),
                ('symmetry3', models.FloatField()),
                ('fractal_dimension3', models.FloatField()),
            ],
        ),
    ]

