# Generated by Django 5.1.6 on 2025-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bc',
            name='patient_id',
            field=models.IntegerField(default=880016212),
            preserve_default=False,
        ),
    ]
