# Generated by Django 5.1.6 on 2025-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANN', '0002_bc_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('contract_address', models.CharField(max_length=42)),
                ('abi', models.TextField()),
                ('bytecode', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
